version: "3.8"

services:
  mongodb:
    env_file: ./.env
    image: mongo:5.0.2
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_PORT:$MONGODB_PORT
    volumes:
      - db:/data/db
  app:
    env_file: ./.env
    depends_on:
      - mongodb
    build: .
    restart: always
    ports:
      - $PARSE_SERVER_PORT:$PARSE_SERVER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_PORT
    stdin_open: true
    tty: true
  parse-dashboard:
    env_file: ./.env
    image: parseplatform/parse-dashboard
    environment:
      - HOST=$PARSE_DASHBOARD_HOST
      - PORT=$PARSE_DASHBOARD_PORT
      - MOUNT_PATH=$PARSE_DASHBOARD_MOUNT_PATH
      - PARSE_DASHBOARD_SERVER_URL=$PARSE_DASHBOARD_SERVER_URL
      - PARSE_DASHBOARD_MASTER_KEY=$PARSE_DASHBOARD_MASTER_KEY
      - PARSE_DASHBOARD_APP_ID=$PARSE_DASHBOARD_APP_ID
      - PARSE_DASHBOARD_APP_NAME=$PARSE_DASHBOARD_APP_NAME
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=$PARSE_DASHBOARD_ALLOW_INSECURE_HTTP
      - PARSE_DASHBOARD_USER_ID=$PARSE_DASHBOARD_USER_ID
      - PARSE_DASHBOARD_USER_PASSWORD=$PARSE_DASHBOARD_USER_PASSWORD
    ports:
      - $PARSE_DASHBOARD_PORT:$PARSE_DASHBOARD_PORT
    depends_on:
      - app
    volumes:
      - ./parse-dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json

volumes:
  db: